--
-- PostgreSQL database dump
--

\restrict fCGheGFw1WzvfiJfg39GYnezfRdQow339MN3r8GTRW6QwYgNBnhv89jwCo2caqt

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cars; Type: TABLE; Schema: public; Owner: abastecefacil_user
--

CREATE TABLE public.cars (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    license_plate character varying(255) NOT NULL,
    model character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.cars OWNER TO abastecefacil_user;

--
-- Name: cars_id_seq; Type: SEQUENCE; Schema: public; Owner: abastecefacil_user
--

ALTER TABLE public.cars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gas_stations; Type: TABLE; Schema: public; Owner: abastecefacil_user
--

CREATE TABLE public.gas_stations (
    id bigint NOT NULL,
    address character varying(255) NOT NULL,
    business_hours character varying(255),
    cep character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    cnpj character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    district character varying(255) NOT NULL,
    fantasy_name character varying(255),
    is_active boolean NOT NULL,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(255),
    state character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.gas_stations OWNER TO abastecefacil_user;

--
-- Name: gas_stations_id_seq; Type: SEQUENCE; Schema: public; Owner: abastecefacil_user
--

ALTER TABLE public.gas_stations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gas_stations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incidents; Type: TABLE; Schema: public; Owner: abastecefacil_user
--

CREATE TABLE public.incidents (
    id bigint NOT NULL,
    car_plate character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255) NOT NULL,
    occurrence_date date NOT NULL,
    title character varying(255) NOT NULL,
    user_name character varying(255) NOT NULL
);


ALTER TABLE public.incidents OWNER TO abastecefacil_user;

--
-- Name: incidents_id_seq; Type: SEQUENCE; Schema: public; Owner: abastecefacil_user
--

ALTER TABLE public.incidents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: abastecefacil_user
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.users OWNER TO abastecefacil_user;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: abastecefacil_user
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: cars; Type: TABLE DATA; Schema: public; Owner: abastecefacil_user
--

INSERT INTO public.cars VALUES
	(1, true, '2025-12-13 19:14:00.290859', 'MGM5H18', 'Spacefox', NULL),
	(2, true, '2025-12-13 19:14:15.558009', 'ABC1234', 'Camaro', NULL);


--
-- Data for Name: gas_stations; Type: TABLE DATA; Schema: public; Owner: abastecefacil_user
--

INSERT INTO public.gas_stations VALUES
	(1, 'Rua Rudolfo Finder, 225', '06:00 - 22:00', '89226120', 'Joinville', '12.345.678/0001-26', '2025-12-13 19:15:59.125035', 'Aventureiro', 'Posto do Pedrinho Filial 3', true, -26.25176380, -48.82228540, 'Posto Do Pedrinho', '(47) 9 9623-5372', 'SC', NULL),
	(2, 'Rua Dom Gregorio Warmeling, 1117', '06:00 - 22:00', '89226526', 'Joinville', '12.345.678/0001-27', '2025-12-13 19:18:38.032551', 'Jardim Paraiso', 'Posto do Pedrinho Filial 3', true, -26.21141230, -48.82248980, 'Posto Do Pedrinho', '(47) 9 9623-5372', 'SC', NULL);


--
-- Data for Name: incidents; Type: TABLE DATA; Schema: public; Owner: abastecefacil_user
--

INSERT INTO public.incidents VALUES
	(1, 'MGM5H18', '2025-12-13 19:20:57.369351', 'O veículo apresentou uma pane no motor durante o abastecimento. Foi necessário interromper o processo e acionar a manutenção.', '2025-10-31', 'Pane no motor', 'Pedro Henrique');


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: abastecefacil_user
--

INSERT INTO public.users VALUES
	(1, '2025-12-13 19:12:57.653927', 'pedro@email.com', true, 'Pedro Silva', '$2a$10$E2UPv7arXmp3q0LzV5v1beRnH51/G51fJtYjW.u2FpYxJ9QjCj7.y', NULL),
	(2, '2025-12-13 19:13:46.909054', 'rafaela.mendes@email.com', true, 'Rafaela Mendes de Souza', '$2a$10$E2UPv7arXmp3q0LzV5v1beRnH51/G51fJtYjW.u2FpYxJ9QjCj7.y', NULL),
	(3, '2026-08-03 19:00:00.000000', 'admin@abastecefacil.com', true, 'Administrador', '$2a$10$E2UPv7arXmp3q0LzV5v1beRnH51/G51fJtYjW.u2FpYxJ9QjCj7.y', NULL);


--
-- Name: cars_id_seq; Type: SEQUENCE SET; Schema: public; Owner: abastecefacil_user
--

SELECT pg_catalog.setval('public.cars_id_seq', 2, true);


--
-- Name: gas_stations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: abastecefacil_user
--

SELECT pg_catalog.setval('public.gas_stations_id_seq', 2, true);


--
-- Name: incidents_id_seq; Type: SEQUENCE SET; Schema: public; Owner: abastecefacil_user
--

SELECT pg_catalog.setval('public.incidents_id_seq', 1, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: abastecefacil_user
--

SELECT pg_catalog.setval('public.users_id_seq', 3, true);


--
-- Name: cars cars_pkey; Type: CONSTRAINT; Schema: public; Owner: abastecefacil_user
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_pkey PRIMARY KEY (id);


--
-- Name: gas_stations gas_stations_pkey; Type: CONSTRAINT; Schema: public; Owner: abastecefacil_user
--

ALTER TABLE ONLY public.gas_stations
    ADD CONSTRAINT gas_stations_pkey PRIMARY KEY (id);


--
-- Name: incidents incidents_pkey; Type: CONSTRAINT; Schema: public; Owner: abastecefacil_user
--

ALTER TABLE ONLY public.incidents
    ADD CONSTRAINT incidents_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: abastecefacil_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: gas_stations uk8atkmpnk417qqgkf1r1gw7ujk; Type: CONSTRAINT; Schema: public; Owner: abastecefacil_user
--

ALTER TABLE ONLY public.gas_stations
    ADD CONSTRAINT uk8atkmpnk417qqgkf1r1gw7ujk UNIQUE (cnpj);


--
-- Name: cars ukdbc9idlyetvssufb2vxicvb87; Type: CONSTRAINT; Schema: public; Owner: abastecefacil_user
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT ukdbc9idlyetvssufb2vxicvb87 UNIQUE (license_plate);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: abastecefacil_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict fCGheGFw1WzvfiJfg39GYnezfRdQow339MN3r8GTRW6QwYgNBnhv89jwCo2caqt

