-- Baseline do schema gerado pelo Hibernate (ddl-auto: update) ate a introducao do Flyway.
-- Reproduz exatamente o resultado de pg_dump --schema-only do banco atual.
-- Aditiva e idempotente: nenhum DROP, nenhuma alteracao destrutiva.
-- Em bases ja existentes o Flyway registra baseline e esta migration nao roda.

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS gas_stations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    address character varying(255) NOT NULL,
    business_hours character varying(255),
    cep character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    cnpj character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    district character varying(255) NOT NULL,
    fantasy_name character varying(255),
    is_active boolean NOT NULL,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(255),
    state character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT gas_stations_pkey PRIMARY KEY (id),
    CONSTRAINT uk8atkmpnk417qqgkf1r1gw7ujk UNIQUE (cnpj)
);

CREATE TABLE IF NOT EXISTS cars (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    license_plate character varying(255) NOT NULL,
    model character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT cars_pkey PRIMARY KEY (id),
    CONSTRAINT ukdbc9idlyetvssufb2vxicvb87 UNIQUE (license_plate)
);

CREATE TABLE IF NOT EXISTS incidents (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    car_plate character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255) NOT NULL,
    occurrence_date date NOT NULL,
    title character varying(255) NOT NULL,
    user_name character varying(255) NOT NULL,
    CONSTRAINT incidents_pkey PRIMARY KEY (id)
);
