-- Convencao de nomenclatura de constraints, valida da V2 em diante:
--   pk_<tabela>                  chave primaria
--   uk_<tabela>_<coluna>         restricao de unicidade
--   fk_<tabela>_<referencia>     chave estrangeira
-- A V1 e excecao: por ser baseline de um schema pre-existente, preservou os nomes
-- gerados pelo Hibernate (uk6dotkott2kjsp8vw4d0m25fb7 e afins). Nomes novos sao
-- sempre explicitos e legiveis.
--
-- Carga inicial: apenas Joinville (JOI) e Florianopolis (FLN). A FIESC tem 13
-- regionais no total; as 11 restantes entram numa migration posterior, quando o
-- cliente confirmar a lista oficial.
--
-- Aditiva e idempotente: nenhum DROP, nenhuma alteracao destrutiva.

CREATE TABLE IF NOT EXISTS regionais (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo boolean NOT NULL,
    created_at timestamp(6) without time zone,
    nome character varying(255) NOT NULL,
    sigla character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT pk_regionais PRIMARY KEY (id),
    CONSTRAINT uk_regionais_sigla UNIQUE (sigla)
);

INSERT INTO regionais (nome, sigla, ativo, created_at)
VALUES ('Joinville', 'JOI', true, now()),
       ('Florianópolis', 'FLN', true, now())
ON CONFLICT ON CONSTRAINT uk_regionais_sigla DO NOTHING;
