-- Convencao de nomenclatura de constraints: ver V2__regionais.sql.
-- Aditiva e idempotente: nenhum DROP, nenhuma alteracao destrutiva.
-- Auto-suficiente: nao depende de nenhuma tabela anterior. Cria uma tabela isolada,
-- entao roda igual no caminho Flyway (base limpa) e no caminho init-scripts/dump.sql
-- (base de desenvolvimento, onde a V1 nunca executa por causa do baseline).
--
-- Extensao da convencao: a V2 fixou pk_, uk_ e fk_, e nao previu indice nao-unico.
-- Da V5 em diante vale tambem ix_<tabela>_<coluna>. Como o uk_users_matricula da V4,
-- ix_tokens_acesso_email aparece em pg_indexes e NAO em pg_constraint.
--
-- Nao ha FK para users, de proposito: o token e solicitado por e-mail e o usuario
-- pode nao existir no momento da solicitacao. Guardar o e-mail mantem o fluxo de
-- recuperacao com a mesma resposta para conta existente e inexistente.
--
-- token_hash guarda o SHA-256 hexadecimal do token, nunca o valor em claro. Uma
-- consulta direta nesta tabela nao devolve nada que sirva para autenticar.
-- usado_em significa consumo real pelo usuario; a invalidacao por substituicao
-- (gerar um token novo) e feita expirando o anterior, nao marcando-o como usado.

CREATE TABLE IF NOT EXISTS tokens_acesso (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    expira_em timestamp(6) without time zone NOT NULL,
    finalidade character varying(255) NOT NULL,
    ip_solicitante character varying(255),
    token_hash character varying(255) NOT NULL,
    usado_em timestamp(6) without time zone,
    CONSTRAINT pk_tokens_acesso PRIMARY KEY (id),
    CONSTRAINT uk_tokens_acesso_token_hash UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS ix_tokens_acesso_email ON tokens_acesso (email);
